### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGeometry/PolygonClipping.jl#1]
I'm in need of polygon clipping.
As issues are not available at the original repository: helenchg/PolygonClipping.jl, I just forked this into JuliaGeometry.
@sjkelly @helenchg, would it be okay to move this package into JuliaGeometry?
And was this package actually functional on Julia 0.3? In other words, is it even worth porting this to `GeometryTypes` and Julia 0.5?

Best,
Simon

**Comment by sjkelly** [comment]
I'd say Clipper.jl is superior. PolygonClipping morphed into a larger closed source library. The only decent algorithm to use would be Horman Agathos here. Everything else in this snapshot is pretty buggy and not worth the effort.

**Comment by SimonDanisch** [comment]
Good to know!
I was able to fix the biggest worry with Clipper.jl:
https://github.com/Voxel8/Clipper.jl/pull/20, so I guess that's the way to
got then!

2016-12-21 19:38 GMT+01:00 Steve Kelly <notifications@github.com>:

**Comment by sjkelly** [comment]
Great! Clipper is by far the most robust clipping library. There are a few areas you could see 2-4x performance gains but by sacrificing numerical precision. For visuals I believe there are ways to use OpenGL to make things faster where accuracy is not a concern. Here are some papers from my past research for your reference: https://www.zotero.org/kd2cca/items/collectionKey/PM3MZX3N

**Comment by mkborregaard** [comment]
So has Horman Agathos been moved somewhere else? Or can I just copy the code to where I need it?

**Comment by sjkelly** [comment]
I updated this for 1.0 and added a warning to the readme. My plan is to move everything useful to [PolygonOps.jl](https://github.com/JuliaGeometry/PolygonOps.jl).
